# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo landing page theme powered by Hugo Blox website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: "Cúmulo"
    button:
      enable: true
      text: 'Conversemos'
      url: 'mailto:somoscumulo@gmail.com'
    show_search: true
    show_theme_chooser: true

appearance:
  fonts:
    # Carga desde Google Fonts (familias y pesos)
    google_fonts: "Playfair Display:ital,wght@0,400;0,600;0,700;1,400;1,600|Inter:wght@300;400;500;600;700"
    # Mapea familias por área
    heading: "Playfair Display"
    body: "Inter"
    nav: "Inter"
    monospace: "ui-monospace"

# Site footer
footer:
  copyright:
    notice: '© {year} My Company'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
